name: Tokyo Night Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *" # يومياً
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean old Snake
        run: |
          mkdir -p output
          rm -f ./output/github-contribution-grid-snake-dark.svg

      - name: Generate Snake
        uses: platane/snk@v3
        with:
          github_user_name: niatifatah-art
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            output/github-contribution-grid-snake-dark.svg
          args: |
            --palette "#1a1b27,#7aa2f7,#bb9af7"

      - name: Commit & Push Snake
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add ./output/github-contribution-grid-snake-dark.svg
          git commit -m "Update Tokyo Night Snake" || echo "No changes to commit"
          git push || echo "Push failed (maybe no changes)"
